### ISSUE TITLE
Custom Media Queries

### ISSUE THREAD

**Issue by ramiy** [web-platform-tests/interop#421]
### Description

The [Media Queries Level 5](https://www.w3.org/TR/mediaqueries-5/) specification defines “[Custom Media Queries](https://www.w3.org/TR/mediaqueries-5/#custom-mq)” as named aliases for longer and more complex media queries. With custom media queries developers define them once and use them in multiple places, simplifying the process of updating the media query to a single line of code.

Example:

```css
@custom-media --desktop (max-width: 70em);
@custom-media --mobile (max-width: 40em);

@media screen and (--desktop) {
  /* styles */
}
@media screen and (--mobile) {
  /* styles */
}
@media print and (--desktop) {
  /* styles */
}
@media print and (--mobile) {
  /* styles */
}
```

Furthermore, with the help of JS `CSS.customMedia.set()`, developers will be able to change breakpoints dynamically.

### Specification

https://www.w3.org/TR/mediaqueries-5/#custom-mq

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

### Browser bug reports

https://bugs.chromium.org/p/chromium/issues/detail?id=1234172

### Developer discussions

https://open-props.style/#media-queries

### Workarounds

this can be emulated using style queries (https://github.com/web-platform-tests/interop/issues/433):
```
@media (width <= 40em) {
  :root { --screen: mobile; }
}
@media (width <= 70em) {
  :root { --screen: desktop; }
}

@container style(--screen: mobile) {
  /* styles */
}

@container style(--screen: desktop) {
  /* styles */
}
```
### Accessibility Impact

No accessibility impact.

### Privacy Impact

No privacy impact.

**Comment by frehner** [comment]
Bug report for Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1744292

Bug report for WebKit:
https://bugs.webkit.org/show_bug.cgi?id=233820

**Comment by mayank99** [comment]
this can be emulated using style queries (#433):

```css
@media (width <= 40em) {
  :root { --screen: mobile; }
}
@media (width <= 70em) {
  :root { --screen: desktop; }
}

@container style(--screen: mobile) {
  /* styles */
}

@container style(--screen: desktop) {
  /* styles */
}
```
