### ISSUE TITLE
Carryover evaluation: CSS `:has()` pseudo-class

### ISSUE THREAD

**Issue by mayank99** [web-platform-tests/interop#432]
### Description

MDN description:
> The functional `:has()` CSS [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) represents an element if any of the [relative selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure#relative_selector) that are passed as an argument match at least one element when anchored against this element. This pseudo-class presents a way of selecting a parent element or a previous sibling element with respect to a reference element by taking a [relative selector list](https://developer.mozilla.org/en-US/docs/Web/CSS/Selector_list#relative_selector_list) as an argument.

Example:
```css
/* Selects an h1 heading with a
paragraph element that immediately follows
the h1 and applies the style to h1 */
h1:has(+ p) {
  margin-bottom: 0;
}
```

### Specification

https://drafts.csswg.org/selectors-4/#relational

### Tests

https://wpt.fyi/results/css/selectors?q=has

### Current Implementations

- [X] Blink
- [ ] Gecko
- [X] WebKit

### Browser bug reports

https://bugzilla.mozilla.org/show_bug.cgi?id=418039

### Polls & Surveys

https://2023.stateofcss.com/en-US/features/other-features#has_selector

### Other

We still have a few months left in 2023 so there's a chance this might get implemented in Gecko, in which case this doesn't need to be part of interop 2024. 🤷
