### ISSUE TITLE
CSS anchor positioning

### ISSUE THREAD

**Issue by mayank99** [web-platform-tests/interop#455]
### Description

The CSS anchor positioning API allows for elements to be positioned relative to one or more "anchor" elements (rather than relative to a containing block).

This is done by evaluating the `anchor()` functions into pixel values, and then running regular CSS positioned layout (`fixed` or `absolute`).

Example usage:
```css
.anchor {
  anchor-name: --my-anchor;
}

.anchored {
  position: fixed;

  anchor-default: --my-anchor; /* Sets the default target of the anchor() function */
  left: anchor(right);         /* Aligns left edge with anchor's right edge */

  position-fallback: --top-then-bottom; /* To account for overflowing viewport */
}

@position-fallback --top-then-bottom {
  @try {
    bottom: anchor(top); /* Aligns bottom edge with anchor's top edge */
  }
  @try {
    top: anchor(bottom); /* Aligns top edge with anchor's bottom edge */
  }
}
```

Crucially, there is no JavaScript that would otherwise be needed to calculate the position of the anchor element.

Also it can be combined with the popover api (#423) to style elements in the top layer, thus avoiding any stacking context issues which would otherwise require even more JavaScript to work around. Combining these two apis also creates an implicit anchor which can be used to avoid specifying a custom `anchor-name`.

### Specification

https://drafts.csswg.org/css-anchor-position-1/

### Tests

https://wpt.fyi/results/css/css-anchor-position

### Current Implementations

- [ ] Blink (behind a flag)
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Blink: https://chromestatus.com/feature/5124922471874560
Gecko: https://github.com/mozilla/standards-positions/issues/794
Webkit: https://github.com/WebKit/standards-positions/issues/167

### Browser bug reports

Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=1309178
Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
Webkit: ?

### Developer discussions

Chrome article with examples: https://developer.chrome.com/blog/tether-elements-to-each-other-with-css-anchor-positioning/#examples

### Workarounds

Lots of JavaScript:
- https://github.com/oddbird/css-anchor-positioning
- https://floating-ui.com/

### Other

Given that Webkit feels the spec is not mature enough (https://github.com/WebKit/standards-positions/issues/167#issuecomment-1708871010) and they have [ideas](https://fantasai.inkedblade.net/style/specs/css-anchor-exploration/) for improvements, it may not be a good idea to make this part of Interop 2024. But this could change in the coming months. I just wanted to bring it up now ahead of time, and it's also just nice to have all these links in one place (can be easily referenced in next year's proposal for example).
